;

MAJORVERSION	EQU	4
MINORVERSION	EQU	09

CONFIGVERSION	EQU	22

BLACKBITS	EQU	1		; INCLUDE BLACKLIST SUPPORT


VERSIONSTRING	EQU	<'4.10e for Win32'>

TNC2		EQU	0		; NO SUPPORT FOR TNC2 MODE


DATESTRING	EQU	<'May 2008'>


NAMESTRING	EQU	<'G8BPQ'>
CONFIGPROG	EQU	<'BPQCFG.EXE'>
CONFIGNAME	EQU	<'BPQCFG.BIN'>
NODESNAME	EQU	<'BPQNODES'>
DUMPNAME	EQU	<'BPQDUMP'>

